package dev.minecraftagent.client.transfer;

public enum ViewTransferFailure {
  INVALID_DESCRIPTOR,
  ACTIVE_TRANSFER_LIMIT,
  CONNECTION_BYTE_BUDGET_EXCEEDED,
  DUPLICATE_TRANSFER,
  UNKNOWN_TRANSFER,
  TRANSFER_EXPIRED,
  GENERATION_MISMATCH,
  CHUNK_INDEX_OUT_OF_RANGE,
  CHUNK_DUPLICATE,
  CHUNK_LENGTH_OUT_OF_RANGE,
  CHUNK_BASE64_INVALID,
  CHUNK_LENGTH_MISMATCH,
  CHUNK_HASH_MISMATCH,
  CONTENT_COMPRESSED_LENGTH_MISMATCH,
  CONTENT_DECOMPRESSION_FAILED,
  CONTENT_UNCOMPRESSED_LENGTH_MISMATCH,
  CONTENT_HASH_MISMATCH,
  CONTENT_UTF8_INVALID
}
